// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD80HxPyaKU9VIvOA70jRYxgjndV6eVkfo',
    appId: '1:1029589835870:web:eb1761d41e0d65529e14cf',
    messagingSenderId: '1029589835870',
    projectId: 'capstone-2b4a9',
    authDomain: 'capstone-2b4a9.firebaseapp.com',
    storageBucket: 'capstone-2b4a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTXUiMxIk-0N5Jn80Ht2kSb6yoe0waUA',
    appId: '1:1029589835870:android:81b4bfa3028d8bf49e14cf',
    messagingSenderId: '1029589835870',
    projectId: 'capstone-2b4a9',
    storageBucket: 'capstone-2b4a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsWUxs2jBEtHFugygVrY2A375tVMENeY',
    appId: '1:1029589835870:ios:faafc6069e44777f9e14cf',
    messagingSenderId: '1029589835870',
    projectId: 'capstone-2b4a9',
    storageBucket: 'capstone-2b4a9.firebasestorage.app',
    iosBundleId: 'com.example.capstoneUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsWUxs2jBEtHFugygVrY2A375tVMENeY',
    appId: '1:1029589835870:ios:faafc6069e44777f9e14cf',
    messagingSenderId: '1029589835870',
    projectId: 'capstone-2b4a9',
    storageBucket: 'capstone-2b4a9.firebasestorage.app',
    iosBundleId: 'com.example.capstoneUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD80HxPyaKU9VIvOA70jRYxgjndV6eVkfo',
    appId: '1:1029589835870:web:54d9f5403c2c325b9e14cf',
    messagingSenderId: '1029589835870',
    projectId: 'capstone-2b4a9',
    authDomain: 'capstone-2b4a9.firebaseapp.com',
    storageBucket: 'capstone-2b4a9.firebasestorage.app',
  );

}